Fix yarn dev error
Resolves #37.

yarn run v1.22.22
warning package.json: No license field
$ NODE_ENV=dev ./node_modules/.bin/vue-cli-service serve
 ERROR  ReferenceError: require is not defined in ES module scope, you can use import instead
        This file is being treated as an ES module because it has a '.js' file extension and '/home/honma/git/supportability-review-app/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/home/honma/git/supportability-review-app/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/honma/git/supportability-review-app/vue.config.js:1:16
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async Service.run (/home/honma/git/supportability-review-app/node_modules/@vue/cli-service/lib/Service.js:247:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Signed-off-by: Masashi Honma <masashi.honma@gmail.com>